using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Microsoft.Xna.Framework;
using StardewModdingAPI;
using StardewModdingAPI.Events;
using StardewValley;
using StardewValley.Locations;
using StardewValley.Objects;

namespace StardewSim
{
    /// <summary>Layout of one location, as written by `sdv ss-export` (Stardew Sim).</summary>
    public class LocationLayout
    {
        public string Wallpaper { get; set; }
        public string Floor { get; set; }
        public List<FurniturePlacement> Furniture { get; set; } = new();
    }

    public class FurniturePlacement
    {
        public string Id { get; set; }
        public int X { get; set; }
        public int Y { get; set; }
        public int Rotation { get; set; }
        /// <summary>Optional Alternative Textures skin: "packId:variation".</summary>
        public string Skin { get; set; }
    }

    public class LayoutFile
    {
        /// <summary>Decor packs the layout's furniture comes from. If any is missing the layout is skipped
        /// (the Content Patcher side then shows its baked copy instead, so nothing is placed twice).</summary>
        public List<string> RequiresMods { get; set; } = new();
        public Dictionary<string, LocationLayout> Locations { get; set; } = new();
        /// <summary>Furniture item id -> tile actions (e.g. "kitchen", "Billboard", "Jukebox").</summary>
        public Dictionary<string, List<string>> Actions { get; set; } = new();
    }

    public class ModConfig
    {
        public bool PlaceLayouts { get; set; } = true;
        public bool FurnitureActions { get; set; } = true;
        public bool ExportOnSave { get; set; } = true;
    }

    public class ModEntry : Mod
    {
        private const string Key = "Waifuhtr.StardewSim";
        private ModConfig Config;
        private readonly List<(string pack, LayoutFile file)> Layouts = new();
        private readonly Dictionary<string, List<string>> Actions = new(StringComparer.OrdinalIgnoreCase);

        public override void Entry(IModHelper helper)
        {
            this.Config = helper.ReadConfig<ModConfig>();
            foreach (IContentPack pack in helper.ContentPacks.GetOwned())
            {
                LayoutFile file = pack.ReadJsonFile<LayoutFile>("layout.json");
                if (file == null) { this.Monitor.Log($"{pack.Manifest.Name}: no layout.json", LogLevel.Warn); continue; }
                List<string> missing = file.RequiresMods.Where(id => !helper.ModRegistry.IsLoaded(id)).ToList();
                if (missing.Count > 0)
                {
                    this.Monitor.Log($"{pack.Manifest.Name}: skipped, needs {string.Join(", ", missing)} (the location still shows its baked furniture).", LogLevel.Info);
                    continue;
                }
                this.Layouts.Add((pack.Manifest.UniqueID, file));
                this.Monitor.Log($"Loaded layout from {pack.Manifest.Name}: {file.Locations.Count} locations, {file.Actions.Count} actions.", LogLevel.Info);
            }
            // default actions for known decor packs (generated by Stardew Sim from their Calcifer data)
            LayoutFile defaults = helper.Data.ReadJsonFile<LayoutFile>("assets/actions.json");
            foreach (var (_, file) in this.Layouts.Prepend((null, defaults)))
                if (file?.Actions != null)
                    foreach (var pair in file.Actions) this.Actions[pair.Key] = pair.Value;

            helper.Events.GameLoop.DayStarted += this.OnDayStarted;
            helper.Events.Input.ButtonPressed += this.OnButtonPressed;
            helper.Events.GameLoop.Saving += this.OnSaving;
            helper.ConsoleCommands.Add("sim_export", "Export a location's furniture/wallpaper/floor for Stardew Sim.\nUsage: sim_export [location]", (_, args) =>
                this.Export(args.Length > 0 ? Game1.getLocationFromName(args[0]) : Game1.currentLocation));
            helper.ConsoleCommands.Add("sim_place", "Re-run layout placement now (only pieces never placed before).", (_, _) => this.PlaceAll());
        }

        // ---------------------------------------------------------------- placement
        private void OnDayStarted(object sender, DayStartedEventArgs e)
        {
            if (this.Config.PlaceLayouts && Context.IsMainPlayer) this.PlaceAll();
        }

        private void PlaceAll()
        {
            foreach (var (pack, file) in this.Layouts)
                foreach (var (locName, layout) in file.Locations)
                {
                    GameLocation loc = Game1.getLocationFromName(locName);
                    if (loc == null) { this.Monitor.Log($"[{pack}] location '{locName}' not found.", LogLevel.Warn); continue; }
                    this.ApplyDecor(pack, loc, layout);
                    for (int i = 0; i < layout.Furniture.Count; i++)
                        this.PlaceOne(pack, loc, layout.Furniture[i], i);
                }
        }

        private void ApplyDecor(string pack, GameLocation loc, LocationLayout layout)
        {
            if (loc is not DecoratableLocation deco) return;
            string flag = $"{Key}/decor/{pack}";
            if (loc.modData.ContainsKey(flag)) return;
            if (!string.IsNullOrEmpty(layout.Wallpaper)) deco.SetWallpaper(layout.Wallpaper, null);
            if (!string.IsNullOrEmpty(layout.Floor)) deco.SetFloor(layout.Floor, null);
            loc.modData[flag] = "1";
        }

        private void PlaceOne(string pack, GameLocation loc, FurniturePlacement p, int index)
        {
            string flag = $"{Key}/placed/{pack}/{index}/{p.Id}";
            if (loc.modData.ContainsKey(flag)) return; // placed once; the player may move or remove it afterwards
            Item item = ItemRegistry.Create("(F)" + p.Id, allowNull: true);
            if (item is not Furniture furniture) { this.Monitor.Log($"[{pack}] unknown furniture '{p.Id}' (is its content pack installed?)", LogLevel.Warn); return; }
            for (int r = 0; r < p.Rotation; r++) furniture.rotate();
            furniture.TileLocation = new Vector2(p.X, p.Y);
            if (!string.IsNullOrEmpty(p.Skin)) ApplySkin(furniture, p.Skin);
            furniture.modData[$"{Key}/source"] = pack;
            loc.furniture.Add(furniture);
            loc.modData[flag] = "1";
        }

        /// <summary>Best-effort Alternative Textures selection via its modData keys (ignored if AT isn't installed).</summary>
        private static void ApplySkin(Furniture f, string skin)
        {
            int cut = skin.LastIndexOf(':');
            if (cut <= 0) return;
            string owner = skin[..cut], variation = skin[(cut + 1)..];
            f.modData["AlternativeTextureOwner"] = owner;
            f.modData["AlternativeTextureName"] = $"{owner}.{f.Name}";
            f.modData["AlternativeTextureVariation"] = variation;
            f.modData["AlternativeTextureSeason"] = "";
        }

        // ---------------------------------------------------------------- furniture actions
        private void OnButtonPressed(object sender, ButtonPressedEventArgs e)
        {
            if (!this.Config.FurnitureActions || !Context.IsPlayerFree || this.Actions.Count == 0) return;
            if (this.Helper.ModRegistry.IsLoaded("sophie.Calcifer")) return; // Calcifer handles them itself
            if (!(e.Button.IsActionButton() || e.Button == SButton.MouseLeft || e.Button == SButton.ControllerA)) return;

            GameLocation loc = Game1.currentLocation;
            Vector2 tile = e.Button == SButton.ControllerA ? Game1.player.GetGrabTile() : e.Cursor.GrabTile;
            Furniture f = loc?.GetFurnitureAt(tile);
            if (f == null || !this.Actions.TryGetValue(f.ItemId, out List<string> actions) || actions.Count == 0) return;
            if (Vector2.Distance(Game1.player.Tile, tile) > 2.5f) return; // must stand next to it, like vanilla
            if (actions[0].StartsWith("OpenFashionSense") && !this.Helper.ModRegistry.IsLoaded("PeacefulEnd.FashionSense")) return;

            this.Helper.Input.Suppress(e.Button);
            foreach (string action in actions)
                loc.performAction(action, Game1.player, new xTile.Dimensions.Location((int)tile.X, (int)tile.Y));
        }

        // ---------------------------------------------------------------- export for AI tools
        private void OnSaving(object sender, SavingEventArgs e)
        {
            if (!this.Config.ExportOnSave) return;
            this.Export(Game1.currentLocation);
            if (Game1.player.currentLocation?.Name != Game1.player.homeLocation.Value)
                this.Export(Game1.getLocationFromName(Game1.player.homeLocation.Value));
        }

        private void Export(GameLocation loc)
        {
            if (loc == null) { this.Monitor.Log("No such location.", LogLevel.Warn); return; }
            var layout = new LocationLayout();
            if (loc is DecoratableLocation deco)
            {
                layout.Wallpaper = deco.appliedWallpaper.Values.FirstOrDefault();
                layout.Floor = deco.appliedFloor.Values.FirstOrDefault();
            }
            foreach (Furniture f in loc.furniture)
            {
                f.modData.TryGetValue("AlternativeTextureOwner", out string owner);
                f.modData.TryGetValue("AlternativeTextureVariation", out string variation);
                layout.Furniture.Add(new FurniturePlacement
                {
                    Id = f.ItemId, X = (int)f.TileLocation.X, Y = (int)f.TileLocation.Y, Rotation = f.currentRotation.Value,
                    Skin = owner != null ? $"{owner}:{variation}" : null
                });
            }
            var file = new LayoutFile { Locations = { [loc.NameOrUniqueName] = layout } };
            string rel = Path.Combine("exports", $"{loc.NameOrUniqueName}.json");
            this.Helper.Data.WriteJsonFile(rel, file);
            this.Monitor.Log($"Exported {loc.NameOrUniqueName}: {layout.Furniture.Count} furniture -> {rel}", LogLevel.Info);
        }
    }
}
